language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
notifications:
  email: false
install:
  - pip install --upgrade pip
  - pip install numpy pandas jsonschema
script:
  - cd src/Python/
  - python -m unittest discover
